### ISSUE TITLE
problem with minting transaction on mintbase contract

### ISSUE THREAD

**Issue by jilt** [near/near-api-py#20]
Hi people,
my python is not well trained but I can't get this minting call to work

[Python promise](https://github.com/jilt/earendill/blob/main/main.py#L31)
I tested it against the [minting.rs method on the mintbase core contracts](https://github.com/Mintbase/mintbase-core/blob/c8b63c8bbcdabb9350fe03873c608890dda21e8d/store/src/minting.rs#L47) and also checked the metadata syntax with Luis, the mintbase dev, but it doesn't seem to wanna behave...
I'm probably making some stupid mistake that I can't recognise but if someone else can have a look at my code this may be solved very fast,
No message error sadly, access key gets added to the account history but minting transaction doesn't
[This](https://docs.mintbase.xyz/dev/smart-contracts/minting-and-burning) is the mintbase docs for the method

**Comment by frol** [comment]
I don't see anything suspicious in the code from reading it, but it is really hard to suggest anything without being able to reproduce it or seeing an error. One of many wild guesses is that the access key is limited to only making certain function calls, but the function you are calling is not allowed to be used with that key.

**Comment by jilt** [comment]
> 

The problem was my asynch function, i just replaced it, I am sorry because i really wanted to try using promises in python, but now it all works, I just found a little typo [here](https://github.com/near/near-api-py/blob/master/near_api/account.py#L40) in your code, thanks a lot for the quick answer and for your work
