### ISSUE TITLE
Is this library alive and open for collaboration?

### ISSUE THREAD

**Issue by sccheruku** [near/near-api-py#8]
I'd like to find out if this library is dead. 

It appears that the [last meaningful commit](https://github.com/near/near-api-py/commit/6160de1e173ecf3a2e5440a3c3382ee9b9eef5b6) was in 2020, and the [package version](https://pypi.org/project/near-api-py/0.1.0/#history) is only `0.1.0`. Some [submitted PRs](https://github.com/near/near-api-py/pulls) received no love.

I'd love to use this in a python project and I understand that some features are missing. I can make PRs for the missing features. 

What is the best way to collaborate?

**Comment by frol** [comment]
There is no full-time team working on this library these days, but I review the PRs once in a while and merge them (all the PRs are already merged)

**Comment by frol** [comment]
Contributions are welcome!
